<a href="https://colab.research.google.com/github/erikromerovelasco-dev/pandas-/blob/main/CHI_CUADRADO_(Independencia).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import stats

alpha = 0.05


In [ ]:
import numpy as np
from scipy import stats

# Ejercicio 1
tabla1 = np.array([[85, 65],
                   [50, 100]])

chi2, p_value, gl, esperados = stats.chi2_contingency(tabla1, correction=False)

print("Ejercicio 1")
print(f"Chi-cuadrado = {chi2:.4f}")
print(f"p-value = {p_value:.4f}")
print(f"Grados de libertad = {gl}")
print("Frecuencias esperadas:")
print(esperados)

# Assuming 'alpha' is defined elsewhere or should be here
alpha = 0.05 # Add alpha definition if it's not guaranteed to be run from another cell

if p_value < alpha:
    print("Conclusión: Hay relación entre la ciudad y el transporte.\n")
else:
    print("Conclusión: No hay relación entre la ciudad y el transporte.\n")

Ejercicio 1
Chi-cuadrado = 16.4983
p-value = 0.0000
Grados de libertad = 1
Frecuencias esperadas:
[[67.5 82.5]
 [67.5 82.5]]
Conclusión: Hay relación entre la ciudad y el transporte.



In [ ]:
# Ejercicio 2
tabla2 = np.array([[40, 20],
                   [35, 45],
                   [15, 45]])

chi2, p_value, gl, esperados = stats.chi2_contingency(tabla2, correction=False)

print("Ejercicio 2")
print(f"Chi-cuadrado = {chi2:.4f}")
print(f"p-value = {p_value:.4f}")
print(f"Grados de libertad = {gl}")
print("Frecuencias esperadas:")
print(esperados)

if p_value < alpha:
    print("Conclusión: El nivel educativo SÍ influye en el consumo de tabaco.\n")
else:
    print("Conclusión: El nivel educativo NO influye en el consumo de tabaco.\n")


Ejercicio 2
Chi-cuadrado = 21.1279
p-value = 0.0000
Grados de libertad = 2
Frecuencias esperadas:
[[27. 33.]
 [36. 44.]
 [27. 33.]]
Conclusión: El nivel educativo SÍ influye en el consumo de tabaco.



In [ ]:
# Ejercicio 3
tabla3 = np.array([[10, 50],
                   [30, 40],
                   [45, 5]])

chi2, p_value, gl, esperados = stats.chi2_contingency(tabla3, correction=False)

print("Ejercicio 3")
print(f"Chi-cuadrado = {chi2:.4f}")
print(f"p-value = {p_value:.4f}")
print(f"Grados de libertad = {gl}")
print("Frecuencias esperadas:")
print(esperados)

if p_value < alpha:
    print("Conclusión: Existe relación entre la dieta y el nivel de colesterol.\n")
else:
    print("Conclusión: No existe relación entre la dieta y el nivel de colesterol.\n")

Ejercicio 3
Chi-cuadrado = 59.7240
p-value = 0.0000
Grados de libertad = 2
Frecuencias esperadas:
[[28.33333333 31.66666667]
 [33.05555556 36.94444444]
 [23.61111111 26.38888889]]
Conclusión: Existe relación entre la dieta y el nivel de colesterol.

