<a href="https://colab.research.google.com/github/erikromerovelasco-dev/pandas-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from numpy import random

tipos de array

In [3]:
array_0 = np.array(5)
print(array_0)

5


In [5]:
array_1=np.array([1,2,3,4,5])
print(array_1)

[1 2 3 4 5]


In [4]:
array_2=np.array([[1,2,3],[4,5,6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


In [7]:
array_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


index de los arrays

In [8]:
print(array_1[0])

1


In [10]:
print(array_2[1,1])

5


In [11]:
print(array_3[1,0,0])

7


shape

In [40]:
print(array_1.shape)
print(array_2.shape)
print(array_3.shape)

(5,)
(2, 3)
(2, 2, 3)


reshape

In [64]:
print(array_1.reshape(1,5))
print(array_2.reshape(3,2))
print(array_3.reshape(2,3,2))

[[1 2 3 4 5]]
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


concatenar

In [57]:
print(np.concatenate((array_1,array_1)))

[1 2 3 4 5 1 2 3 4 5]


split

In [56]:
print(np.split(array_1,5))

[array([1]), array([2]), array([3]), array([4]), array([5])]


where

In [22]:
print(np.where(array_1==3))

(array([2]),)


ordenar

In [25]:
arrayN = np.array([10,50,2,0,7,6])
print(np.sort(arrayN))

print(np.sort(arrayN)[::-1])

[ 0  2  6  7 10 50]
[50 10  7  6  2  0]


random

In [38]:
numero = random.randint(100,200,1)
print(numero)

[177]


In [35]:
numero = random.randint(10,size=(5))
print(numero)

[7 8 6 3 1]


In [36]:
numero = random.randint(10,size=(2,3))
print(numero)

[[3 3 0]
 [5 6 0]]


numeros decimales

In [52]:
numero = random.rand()
print(round(numero,0))

1.0


In [53]:
nummero2 = random.rand()+5
print(nummero2)


5.2003077426541955


In [54]:
numero3=random.rand(3,5)
print(numero3)

[[0.30996766 0.55048206 0.78643069 0.50708307 0.80826825]
 [0.68248262 0.20599306 0.6640327  0.54041243 0.03093094]
 [0.85123942 0.47712887 0.3336663  0.63846492 0.16552057]]


lista

In [55]:
lista_nombres=["juan,pedro,maria"]
print(random.choice(lista_nombres))

juan,pedro,maria


Crea un array de 10 números aleatorios enteros entre 0 y 100.


In [60]:
array1 = np.random.randint(0, 101, 10)
print(array1)


[71 58 72 49 64 79 40 53  6 22]


Crea un array de 5 números aleatorios decimales entre 0 y 1.

In [61]:
array2 = np.random.rand(5)
print(array2)

[0.14349506 0.11481183 0.94305359 0.82098297 0.56454477]


Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.

In [62]:
a = np.random.randint(0, 100, 5)
b = np.random.randint(0, 100, 5)
concatenado = np.concatenate((a, b))
print(a)
print(b)
print(concatenado)

[47 80 69 68 44]
[42 52 59 72 15]
[47 80 69 68 44 42 52 59 72 15]


 Crear un array de 10 enteros y separarlo en dos arrays de 5

In [65]:
array3 = np.random.randint(0, 100, 10)
parte1, parte2 = np.split(array3, 2)
print(array3)
print(parte1)
print(parte2)


[94 61 83 38 37 98 55 87 66  0]
[94 61 83 38 37]
[98 55 87 66  0]


Crear una matriz 3x3 con decimales entre 0 y 1

In [66]:
matriz = np.random.rand(3,3)
print(matriz)

[[0.67332951 0.95400475 0.99347939]
 [0.5906368  0.77480563 0.44011491]
 [0.67696684 0.00374681 0.93735036]]


Crear un array de 10 enteros y seleccionar 3 al azar

In [73]:
array4 = np.random.randint(0, 100, 10)
seleccion = np.random.choice(array4, 3, replace=False)
print(array4)
print(seleccion)


[28  6 92 85 95  2 55 58  3  5]
[58 58 28]


Crear un array de 10 enteros entre 0 y 100 y calcular la media

In [74]:
array5 = np.random.randint(0, 101, 10)
media = np.mean(array5)
print(array5)
print(media)

[35 16 80 41 42 66 39 53 88 69]
52.9
